### ISSUE TITLE
cannot see the map in rviz

### ISSUE THREAD

**Issue by naiyisiji** [rsasaki0109/pcl_localization_ros2#23]
I add my own pcd map to the map_path parameter but I cannot see my map in rviz. I also play my dataset.db3 but I cannot see the path.  
Could you tell me what happened? Thank U so much!

**Comment by rsasaki0109** [comment]
@naiyisiji 
Does the same problem occur if I launch this package after launching rviz?

**Comment by naiyisiji** [comment]
Sorry I cannot open your dataset link, I only run my dataset and pcd map.

**Comment by rsasaki0109** [comment]
@naiyisiji 
Can you confirm that the `initial_map` topic is published when this package is started? ros2 topic echo initial_map --no-arr.

If it is not published, the value of map_path in the yaml may be incorrect.

**Comment by naiyisiji** [comment]
Hold on. I will test it soon.

**Comment by naiyisiji** [comment]
Now my map is shown in rviz. However I face a new problem. When I use 
ros2 launch pcl_localization_ros2 pcl_localization.launch.py 
I cannot replay my dataset xxxx.db3, which means there are no more message show in terminal ros2 topic hz mytopic. I think my topic message may be blocked. Do you know what happened?

**Comment by rsasaki0109** [comment]
I think rosbag is broken.

**Comment by naiyisiji** [comment]
I am sure my rosbag is nor broken QAQ
x-special/nautilus-clipboard
copy
file:///home/nasky/%E6%A1%8C%E9%9D%A2/254_1681811164_hd.jpeg

**Comment by naiyisiji** [comment]
![254_1681811164_hd](https://user-images.githubusercontent.com/89254461/232740048-289ddee1-d861-40c3-a69b-fd61ba850d7c.jpeg)

**Comment by naiyisiji** [comment]
Thank you Sir. The problem is solved.

**Comment by GauleeJX** [comment]
> @naiyisiji If you run this package after you run rviz, will you have the same problem?

My rviz crashed after running this package. Error like this:rviz2: /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.8/.obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/include/OgreAxisAlignedBox.h:225：void Ogre::AxisAlignedBox::setExtents(const Vector3&, const Vector3&): 假设 ‘(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"’ 失败。

And map is loaded successfully, because terminal returns:
lidar_localization]: Map Size 395053
[lidar_localization_node-1] [INFO] [1730910708.256110969] [lidar_localization]: Initial Map Published
[lidar_localization_node-1] [INFO] [1730910708.269485218] [lidar_localization]: Activating end
But ros2 topic echo /initial_map return nothing, wh

**Comment by rsasaki0109** [comment]
If rviz2 crashes, the configuration file might be corrupted. Try deleting the configuration file and setting up the visualization manually. 
It may also help to reinstall rviz2 with the --reinstall option using apt install.
